spring:
  application:
    name: shop-edge

embedded:
  zookeeper:
    port: 2181

dubbo:
  registry:
    address: zookeeper://192.168.25.129:2181
    timeout: 30000
  consumer:
    timeout: 12000
    retries: 0
server:
  port: 8999

